name: submission-service

replicaCount: 1

image:
  repository: vucongtuanduong/grading-submission
  tag: "v1.0.11"
  pullPolicy: Always

global:
  domain: vucongtuanduong.dpdns.org
  prefix: dev2

spring:
  profilesActive: stg

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
